name: Track Repository Stats

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch Stats
        run: |
          FOLDER="repo-stats"
          mkdir -p $FOLDER
          FILE="$FOLDER/stats.md"
          LAST_UPDATED=$(date -u +'%Y-%m-%d %H:%M:%S UTC')

          REPO_DATA=$(curl -s https://api.github.com/repos/${{ github.repository }})

          STARS=$(echo "$REPO_DATA" | jq '.stargazers_count')
          FORKS=$(echo "$REPO_DATA" | jq '.forks_count')
          WATCHERS=$(echo "$REPO_DATA" | jq '.subscribers_count')

          echo "# Repository Stats" > "$FILE"
          echo "**Last Updated:** $LAST_UPDATED" >> "$FILE"
          echo "" >> "$FILE"
          echo "- Stars: $STARS" >> "$FILE"
          echo "- Forks: $FORKS" >> "$FILE"
          echo "- Watchers: $WATCHERS" >> "$FILE"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add repo-stats/stats.md
          git commit -m "update stats" || echo "no changes"
          git push
